Models/ViewModels/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SchoolApp.Models
{
    public class LoginModelViewModel
    {
        [Required]
        public string Name { get; set; }

        [Required]
        [UIHint("password")]
        public string Password { get; set; }

        public string ReturnUrl { get; set; } = "/";
    }
}

Controllers/UserAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SchoolApp.Models;

// using SchoolApp.Models.Interfaces;
using System.ComponentModel;


namespace SchoolApp.Controllers
{   
    // [Authorize (Roles="Admins")]
    public class UserAccountController : Controller
    {
        //private properties
        private UserManager<User> UserManager;
        private SignInManager<User> signInManager;
     
        //Const
        public UserAccountController(UserManager<User> userManager_, SignInManager<User> signInManager_)
        {
            UserManager = userManager_;
            signInManager = signInManager_;          
        }

        //Action Methods      
        [AllowAnonymous]
        public IActionResult Login(string returnUrl)
        {
            return View(new LoginModel {ReturnUrl = returnUrl } );
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginModel loginModel, string ReturnUrl)
        {
            if(ModelState.IsValid)
            {
                User user = await UserManager.FindByEmailAsync(loginModel.Email);
                var userId = UserManager.GetUserId(User);
                User user_id = await UserManager.FindByIdAsync(userId);

                if(user != null)
                {
                    //await signInManager.SignOutAsync();

                    Microsoft.AspNetCore.Identity.SignInResult result = await signInManager.PasswordSignInAsync(user, loginModel.Password, false, false);

                    if(result.Succeeded)
                    {
                        // if(await UserManager.IsInRoleAsync(user_id,"Applicant"))
                        // {
                             return Redirect(ReturnUrl ?? "/Home/Index");
                        // }
                        // else
                        //     return Redirect(ReturnUrl ?? "/Address/Address");

                        // if(await UserManager.IsInRoleAsync(user_id,"Applicant"))
                        // {
                        //     return Redirect(ReturnUrl ?? "/Account/Profile");
                        // }
                    }
                    else
                        return Redirect(ReturnUrl ?? "/UserAccount/Login");


                        //var result = await SignInManager.PasswordSignInAsync(model.Username, model.Password, model.RememberMe, shouldLockout: false);
                        // switch (result)
                        // {
                        //     case Microsoft.AspNetCore.Identity.SignInStatus.Success: <= (NETCORE 6)
                        //         if(await UserManager.IsInRoleAsync(user.Id,"Admins")) //<= Checking Role and redirecting accordingly.
                        //             return RedirectToAction("Index", "Home");
                        //         else
                        //             return RedirectToAction("profie", "Account");                           
                        //     default:
                        //         ModelState.AddModelError("", "Invalid login attempt.");
                        //         return View(loginModel);
                        // }
                    
                }

                ModelState.AddModelError(nameof(LoginModel.Email), "Invalid username or password");
            }

            ModelState.AddModelError(nameof(LoginModel.Email), "Invalid username or password");
            return View(loginModel);

        }

        public async Task<IActionResult> Logout()
        {
            await signInManager.SignOutAsync();
            return RedirectToAction("Home", "Home");
        }

        [AllowAnonymous]
        public IActionResult AccessDenied()
        {
            return View();
        }

       

    }
}

Views/UserAccount/AccessDenied.cshtml
@{
    ViewData["Title"] = "Access Denied";
    Layout = "_Layout";
}



<div class="text-center">
    <h1 class="display-4">School Online Application</h1>   
    <hr />

    <div class="bg-danger mb-1 p-2 text-white">
        Access Denied
    </div>
    <a asp-action="Index" asp-controller="Home" class="btn btn-primary">
        Return to Homepage
    </a>
</div>

Views/UserAccount/Login.cshtml
@model LoginModel
@{
    Layout = null;
    ViewData["Title"] = "Login";
}

<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"] - SchoolApp</title>

    <!--CUSTOM CSS-->
    @* <link rel="stylesheet" href="~/css/site.css" />  *@
    <link rel="stylesheet" href="~/css/templateStyle.css" />
    
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!--JS Columns-->
    <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet">

    <!--ICONS-->
    <link href="~/lib/bootstrap/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">

     <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

</head>

<body>

  <main>
    <div class="container">

      <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">

              <div class="d-flex justify-content-center py-4">
                <a href="index.html" class="logo d-flex align-items-center w-auto">
                  <img src="assets/img/logo.png" alt="">
                  <span class="d-none d-lg-block">SchoolApp Login</span>
                </a>
              </div><!-- End Logo -->


              <div class="card mb-3">

                <div class="card-body">

                  <div class="pt-4 pb-2">
                    <h5 class="card-title text-center pb-0 fs-4">Login to Your Account</h5>
                    <p class="text-center small">Enter your username & password to login</p>
                  </div>

                  <form asp-action="Login" asp-controller="UserAccount" method="post" class="row g-3 needs-validation" novalidate>

                    <div class="col-12">
                      <div asp-validation-summary="All"></div>
                      <input type="hidden" asp-for="ReturnUrl" />
                      <label for="yourUsername" class="form-label">Username</label>
                      <div class="input-group has-validation">
                        @* <span class="input-group-text" id="inputGroupPrepend"></span> *@
                        <input asp-for="Email" type="email" name="Email" class="form-control" id="yourEmail" required>
                        <div asp-validation-for="Email" class="invalid-feedback">Please enter your username.</div>
                      </div>
                    </div>

                    <div class="col-12">
                      <label for="yourPassword" class="form-label">Password</label>
                      <input asp-for="Password" type="password" name="password" class="form-control" id="yourPassword" required>
                      <div asp-validation-for="Password" class="invalid-feedback">Please enter your password!</div>
                    </div>

                    <div class="col-12">
                      <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="remember" value="true" id="rememberMe">
                        <label class="form-check-label" for="rememberMe">Remember me</label>
                      </div>
                    </div>
                    <div class="col-12">
                      <button class="btn btn-primary w-100" type="submit">Login</button>
                    </div>
                    <div class="col-12">
                      <p class="small mb-0">Don't have account? <a href="~/UserAdmin/Create">Create an account</a></p>
                    </div>
                  </form>

                </div>
              </div>

             
            </div>
          </div>
        </div>

      </section>

    </div>
  </main><!-- End #main -->

  <script src="~/js/site.js" asp-append-version="true"></script>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    @* <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script> *@
    -->

    <script src="https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js" integrity="sha384-GNFwBvfVxBkLMJpYMOABq3c+d3KnQxudP/mGPkzpZSTYykLBNsZEnG2D9G/X/+7D" crossorigin="anonymous" ></script>


</body>

</html>